### ISSUE TITLE
"Create Deck" Button missing?

### ISSUE THREAD

**Issue by buschNT** [unikubehq/frontend#106]
I can't find a "Create Deck" button... not sure if I simply don't see it or if I don't have the rights to create a Deck. Nevertheless, I guess in both cases it would be possible to improve the UI.

If I don't have the rights, it might be nice to see a deactivated button, since this would tell me that I simply don't have the permissions and I could stop searching for the button.

**Comment by SteinRobert** [comment]
Currently we do not provide the user with a UI to create decks. This feature is on the roadmap though:

https://unikube.io/docs/roadmap/dynamic-deck-creation.html

**Comment by buschNT** [comment]
This might be a high priority feature. I personally got completely stuck when I tried to create a Deck (obviously because its not possible yet). Nevertheless, I just had the expectation that after creating a Project, I would be able to create a Deck and get started. I guess many people who just want to try the tool could stop using it at this point. They would now have to got into the Docs or watch the explanation video to see how to process.

Maybe a temporary fix would be a comment: "SOPS missing", or a link to some explanation. Long-term, however, I would expect the "Create Deck" Button ;D

**Comment by SteinRobert** [comment]
>Maybe a temporary fix would be a comment: "SOPS missing", or a link to some explanation.

Well that really depends on the project here. Not every project needs SOPS, even it would be better if all projects made use of it. But maybe we can create some kind of detection which allows us to display the kind of hint your are writing about.

The creation of decks is kind of a complex thing, since you need to create some kind of understanding of the helm charts and k8s manifest to enable the use to kind of drag'n drop k8s resources and manifests into a Deck.

**Comment by buschNT** [comment]
Maybe the issue is/was that I used an empty git repo to create the project. Now I filled it with some helm charts, but maybe I do something wrong, since I see no deck after syncing again. Maybe it would be sufficient to indicate that no deck could be extracted from the provided repo?

**Comment by SteinRobert** [comment]
We just released a new version (1.3.0) for the frontend. It includes an indicator for the project status. This should at least help to find common problems with the project setup.

**Comment by SteinRobert** [comment]
I close this for now. We open an issue as soon as we start working on the [dynamic deck creation feature](https://unikube.io/docs/roadmap/dynamic-deck-creation.html).
