### ISSUE TITLE
Notification to join self created organization

### ISSUE THREAD

**Issue by buschNT** [unikubehq/frontend#133]
I created a new organization and got a notification (the bell) that I was invited to join, but I "joined" with the creation of the organization. I guess this notification is not required? Furthermore I did not get any feedback when I clicked "join".

**Comment by SteinRobert** [comment]
I guess this is a bug in the [orgas](https://github.com/unikubehq/orgas) service then. The frontend only requests the invitation status. Have to check though.

**Comment by buschNT** [comment]
Can be. Then we could maybe shift this issue to the orga service, once its confirmed.

**Comment by SteinRobert** [comment]
@buschNT just pinging. You have any hint on how to reproduce this?

**Comment by buschNT** [comment]
@SteinRobert No. I just tried it again and everything was fine. I close this issue, since I can't reproduce it and thus I guess it is too much effort to track down this issue - if it still exists.
