### ISSUE TITLE
Remove wrong icons from environment

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/frontend#212]
<img width="760" alt="Bildschirmfoto 2021-11-02 um 19 12 30" src="https://user-images.githubusercontent.com/1231105/139921829-bc47b3d8-6ac9-4d38-a0b1-9eb2606eae51.png">

**Comment by tobifroe** [comment]
If I recall correctly, the input components need an icon for everything to align properly (in our setup). Any idea what icons would fit in the title, description and namespace fields here?
