### ISSUE TITLE
Inconsistent icon titles (decks overview)

### ISSUE THREAD

**Issue by tschale** [unikubehq/frontend#228]
On the decks overview page the CLI icon has the title `Icons/Big/CLI` (is this intended, or should it just be `CLI`?), while the edit icon besides it doesn't has an icon.
![image](https://user-images.githubusercontent.com/5681839/140787128-595f70cb-a807-485e-9a3c-e430af38914c.png)

**Comment by SteinRobert** [comment]
I guess the title was generated by Sketch or Figma when the icon was exported.
We should probably add a proper title to all the SVGs for accessibility reasons.
