### ISSUE TITLE
create organization has "skip this for now" + "finish button"

### ISSUE THREAD

**Issue by buschNT** [unikubehq/frontend#247]
I am not sure it the "skip this for now" + "finish button" makes sense. Both have the same outcome.

![Screenshot from 2021-11-12 09-35-03](https://user-images.githubusercontent.com/6874607/141438789-48c6a9df-efc4-4648-a57e-544847e75a4b.png)

**Comment by himanshu007-creator** [comment]
So this line should be deleted instead right?

**Comment by buschNT** [comment]
Hi Himanshu,

> So this line should be deleted instead right?

Yes, I would remove the "Or skip this for now". @SteinRobert Do you agree?

**Comment by SteinRobert** [comment]
Yes that line could be removed, as well as the translations.

**Comment by KNHNam** [comment]
I think the button "Add another" should be included in the fill bar and button Skip below. I edited your UI and I hope you will have another optio
![edit](https://user-images.githubusercontent.com/91792233/141684727-06c22fbb-3e5c-4f09-a680-24c3676d52c2.jpg)
n.

**Comment by SteinRobert** [comment]
Hey @KNHNam thank you very much for your input! 
I have to say I do not agree with moving the "add more" action into the input field. Here are the reasons why:
1. It's unclear what the "+" button does. It's within the field - my (subjectively) first thought would be the button changing something within the field. Not adding another.
2. The "add another" action per se adds another field. It's unclear how the action should look like then (is there a "+" in every field? only in the first field?...). 
3. We actually use the space you placed the "+" button to show a confirmation icon when the invitation was successful.
