### ISSUE TITLE
"Override helm values" button overlaps with save button

### ISSUE THREAD

**Issue by buschNT** [unikubehq/frontend#258]
See screenshots for two different screen sizes using chrome:

![Screenshot from 2021-11-17 14-38-45](https://user-images.githubusercontent.com/6874607/142212167-5f01b3f8-69d0-4174-a763-dfc7978aacd8.png)

![Screenshot from 2021-11-17 14-39-01](https://user-images.githubusercontent.com/6874607/142212170-114a84fb-aa9c-4701-a3c5-8e4cfdf8ff55.png)

**Comment by SteinRobert** [comment]
Thank you very much for your report!
Duplicates #252. Fix is included in the next release.
