### ISSUE TITLE
Renaming project is only superficial

### ISSUE THREAD

**Issue by tschale** [unikubehq/frontend#367]
I'm not sure whether this issue is correctly in the frontend, or whether the problem lies somewhere else.

I renamed a project in the frontend, which also appeared under `unikube project` commands with the new name (_FF AH Keycloak_). However when running `unikiube project up`, the cli tries to create a cluster with the old name/slug (_FF Automation Hub Keycloak 2_):
![image](https://user-images.githubusercontent.com/5681839/148752349-b4a7657b-a65a-4188-bd49-4e56494760d8.png)

**Comment by SteinRobert** [comment]
This looks like a cli issue. Opened an issue in the cli repo.
