### ISSUE TITLE
Editing (saving) a project with another organization set moves the project to that organization

### ISSUE THREAD

**Issue by Schille** [unikubehq/frontend#71]

**Comment by SteinRobert** [comment]
This should not be possible since 1.0.12 (#61), since the last set organization is stored and loaded from the browser's localstorage.
Can you confirm, that this issue has been resolved?

**Comment by SteinRobert** [comment]
€dit: The behaviour can be reproduced by copying the url of a project, changing the organization through the sidebar dropdown and pasting the url into the browser bar again.
