### ISSUE TITLE
"Browse other Projects" list shows projects of all organizations

### ISSUE THREAD

**Issue by Schille** [unikubehq/frontend#72]
The "Browse other Projects" tab when editing a project shows all projects across all organizations.
![image](https://user-images.githubusercontent.com/676722/124126879-68433680-da7b-11eb-804e-66707e5c1977.png)

**Comment by SteinRobert** [comment]
Browse project is a remnant from the earlier designs. Removed in fac80d9908f93b6c1876f679ca97f84b2ff96042
