### ISSUE TITLE
"Join Another Organization" not working

### ISSUE THREAD

**Issue by buschNT** [unikubehq/frontend#79]
The option "Join Another Organization" does not trigger any action.

![Screenshot from 2021-07-14 09-45-56](https://user-images.githubusercontent.com/6874607/125583762-8010f26b-6f81-4d03-9f7e-f35fe3ec2816.png)

**Comment by SteinRobert** [comment]
When we work on #65 we should probably just remove the "join another organization" button since it makes no sense.
One can only be invited to an organization, however there is no way to actively join an organization.
